In [11]:
import os
import numpy as np
import pandas as pd
from numpy import loadtxt
import math
from keras.models import model_from_json
from keras.models import load_model
import h5py
import psycopg2
# Let's import sqlalchemy
import sqlalchemy as db

In [2]:
conn = db.create_engine('postgresql://postgres:postgres@localhost/test01')

try:
    connection = psycopg2.connect(user = "postgres",
                                  password = "123456",
                                  host = "127.0.0.1",
                                  port = "5432",
                                  database = "test01")

    cursor = connection.cursor() 

    query =  """ select "Pregnancies" , "Glucose" ,"BloodPressure" ,
                "SkinThickness" , "Insulin" , "BMI" ,
                "DiabetesPedigreeFunction","Age"
                from "Task_3".diabetes_unscored
                Except
                select "Pregnancies" , "Glucose" , "BloodPressure" ,
                "SkinThickness" , "Insulin" , "BMI" ,
                "DiabetesPedigreeFunction","Age"
                from "Task_3".diabetes_scored ;   """
    df_diabetes = pd.read_sql(query, connection)


except (Exception, psycopg2.Error) as error :
    print ("Error while connecting to PostgreSQL", error)
finally:
        if(connection):
            cursor.close()
            connection.close()
            print("PostgreSQL connection is closed")

PostgreSQL connection is closed

In [3]:
df_diabetes.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,5.0,109.0,75.0,26.0,0.0,36.0,0.546,60.0
1,7.0,129.0,68.0,49.0,125.0,38.5,0.439,43.0
2,4.0,120.0,68.0,0.0,0.0,29.6,0.709,34.0
3,0.0,102.0,52.0,0.0,0.0,25.1,0.078,21.0
4,3.0,191.0,68.0,15.0,130.0,30.9,0.299,34.0
5,0.0,141.0,0.0,0.0,0.0,42.4,0.205,29.0
6,1.0,108.0,60.0,46.0,178.0,35.5,0.415,24.0
7,11.0,85.0,74.0,0.0,0.0,30.1,0.300,35.0
8,1.0,181.0,78.0,42.0,293.0,40.0,1.258,22.0
9,10.0,68.0,106.0,23.0,49.0,35.5,0.285,47.0

In [4]:
df_diabetes['outcome']= ''

In [5]:
# load json and create model
json_file = open('model.json', 'r')
model_json = json_file.read()
json_file.close()
model = model_from_json(model_json)
# load weights into new model
model.load_weights("model.h5")
print("model loaded")

model loaded

In [6]:
M_array = df_diabetes.iloc[:,:-1].values
predicted_Values = model.predict(M_array)

WARNING:tensorflow:From /home/mhassan01/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

In [7]:
pred_bin = []
for i in predicted_Values:
    for element in i :
        if element >= 0.5:
            bin_val = 1
        else :
            bin_val = 0
        pred_bin.append(bin_val)


df_diabetes['outcome'] = pred_bin

In [9]:
# Let's import sqlalchemy
import sqlalchemy as db

try:
    conn = db.create_engine('postgresql://postgres:123456@localhost/test01')
    df_diabetes.to_sql(name = 'diabetes_scored',schema ='Task_3',con=conn ,index = False, if_exists='append')
    print("dataframe loaded to the diabetes_scored Table")

except (Exception, psycopg2.Error) as error :
    print ("PostgreSQL connection Error", error)
finally:
        if(connection):
            cursor.close()
            connection.close()
#,index = False , if_exists='append'

dataframe loaded to the diabetes_scored Table

In [10]:
df_diabetes.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,outcome
0,5.0,109.0,75.0,26.0,0.0,36.0,0.546,60.0,0
1,7.0,129.0,68.0,49.0,125.0,38.5,0.439,43.0,1
2,4.0,120.0,68.0,0.0,0.0,29.6,0.709,34.0,1
3,0.0,102.0,52.0,0.0,0.0,25.1,0.078,21.0,0
4,3.0,191.0,68.0,15.0,130.0,30.9,0.299,34.0,1
5,0.0,141.0,0.0,0.0,0.0,42.4,0.205,29.0,1
6,1.0,108.0,60.0,46.0,178.0,35.5,0.415,24.0,0
7,11.0,85.0,74.0,0.0,0.0,30.1,0.300,35.0,0
8,1.0,181.0,78.0,42.0,293.0,40.0,1.258,22.0,1
9,10.0,68.0,106.0,23.0,49.0,35.5,0.285,47.0,0